{% set name = "rmm" %}
{% set version = "22.04.01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/rmm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2989ecac7d29f1104f3bd8bf328f3345398faaf2164eea86a755ff204e4214fb
  folder: rmm
  patches:
    - py_ver.diff

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler_version !=  "11.2")]
  script_env:
    - INSTALL_PREFIX=${PREFIX}
    - CUDA_HOME  # [ppc64le or aarch64]
  script:
    - cd rmm/python
    - {{ PYTHON }} -m pip install . --no-deps -vv
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
  ignore_run_exports:
    - spdlog
    - librmm

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - librmm ={{ version }}
    - python
    - pip
    - setuptools
    - cython >=0.29,<0.30
    - spdlog >=1.8.5,<2
    - cuda-python 11.6
    - thrust
    - cub
  run:
    - python
    - numba >=0.49
    - numpy
    - {{ pin_compatible('cuda-python', min_pin='x.x', max_pin='x.x') }}

test:
  imports:
    - rmm

about:
  home: https://github.com/rapidsai/rmm
  license: Apache-2.0
  license_family: APACHE
  license_file: rmm/LICENSE
  summary: RAPIDS Memory Manager

extra:
  recipe-maintainers:
    - alhad-deshpande
    - leofang
