{% set name = "rmm" %}
{% set version = "23.10.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/rmm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4e2408073662fdfd92ca21d87f7d2afc64d2595fd5a1e3fa321d3472cfbd7f7a
  folder: rmm

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler == "None")]
  script_env:
    - CMAKE_GENERATOR=Ninja
    - INSTALL_PREFIX=${PREFIX}
  script:
    - export CMAKE_ARGS="${CMAKE_ARGS} -DFIND_RMM_CPP=ON -DThrust_ROOT=${PREFIX}/include/rapids/thrust/"
    - cd rmm/python
    - {{ PYTHON }} -m pip install . --no-deps -vv
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
  ignore_run_exports:
    - spdlog
    - librmm

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.26.4
    - ninja
  host:
    - cuda-cudart-dev        # [(cuda_compiler_version or "").startswith("12")]
    - librmm ={{ version }}
    - python
    - pip
    - tomli                  # [py<311]
    - cython >=3.0.0
    - cuda-python ==11.7.1   # [(cuda_compiler_version or "").startswith("11")]
    - cuda-python ==12.0.0   # [(cuda_compiler_version or "").startswith("12")]
    - scikit-build >=0.13.1
  run:
    - python
    - numba >=0.57
    - numpy >=1.21

test:
  imports:
    - rmm

about:
  home: https://github.com/rapidsai/rmm
  license: Apache-2.0
  license_family: APACHE
  license_file: rmm/LICENSE
  summary: RAPIDS Memory Manager

extra:
  recipe-maintainers:
    - alhad-deshpande
    - leofang
