{% set name = "rmm" %}
{% set version = "22.02.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/rmm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 90ed8e21e3e82b9d55fe2f45afd836489c2d07b842d4cf9eadf5ff07849ff768
  folder: rmm

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler_version !=  "11.2") or (aarch64) or (py < 37) or (py >= 39)]

  script_env:
    - INSTALL_PREFIX=${PREFIX}
    - CUDA_HOME  # [ppc64le]

  script:
    - cd rmm/python
    - {{ PYTHON }} -m pip install . --no-deps -vv

  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
  ignore_run_exports:
    - spdlog
    - librmm
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - librmm ={{ version }}
    - python
    - pip
    - setuptools
    - cython >=0.29,<0.30
    - spdlog >=1.8.5,<2
  run:
    - python
    - numba >=0.49
    - numpy
    - {{ pin_compatible('cudatoolkit', max_pin='x', lower_bound='11.2') }} # cudatoolkit >=11.2,<12.0.0

test:
  imports:
    - rmm

about:
  home: https://github.com/rapidsai/rmm
  license: Apache-2.0
  license_family: APACHE
  license_file: rmm/LICENSE
  summary: RAPIDS Memory Manager

extra:
  recipe-maintainers:
    - alhad-deshpande
    - leofang
